# === FONT ===
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# === WINDOW ===
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

# === TRANSPARENCIA ===
background_opacity 0.65
dynamic_background_opacity yes

# === CURSOR ===
cursor_shape beam
cursor_blink_interval 0.5

# === SCROLLBACK ===
scrollback_lines 10000

# === TABS ===
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# === COLORS: Catppuccin Mocha con fondo NEGRO puro ===
foreground           #cdd6f4
background           #000000
selection_foreground #1e1e2e
selection_background #f5e0dc

cursor               #f5e0dc
cursor_text_color    #000000

# Tabs
active_tab_foreground   #000000
active_tab_background   #cdd6f4
inactive_tab_foreground #cdd6f4
inactive_tab_background #45475a

url_color #f5e0dc

active_border_color   #b4befe
inactive_border_color #6c7086

# Normal
color0  #45475a
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #f5c2e7
color6  #94e2d5
color7  #bac2de

# Bright
color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #a6adc8

# === KEYBINDS ===
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+enter new_window
map ctrl+shift+t new_tab
map ctrl+shift+w close_window
map ctrl+shift+q close_tab
