# === Fuzzel: app launcher ===

font=JetBrainsMono Nerd Font:size=11
dpi-aware=yes
prompt="❯ "
icon-theme=Adwaita
icons-enabled=yes
fields=name,generic,comment,categories,filename,keywords
terminal=kitty
list-executables-in-path=no
anchor=center
lines=6
width=28
horizontal-pad=16
vertical-pad=12
inner-pad=6
line-height=20
letter-spacing=0
hide-when-prompt-empty=no
exit-on-keyboard-focus-loss=yes

[colors]
background=00000099
text=e6e6e6ff
prompt=f35638ff
input=e6e6e6ff
match=f35638ff
selection=2a2a2aaa
selection-text=ffffffff
selection-match=f35638ff
border=404040cc
counter=707070ff
placeholder=707070ff

[border]
width=1
radius=12

[dmenu]
exit-immediately-if-empty=yes
