exec-once = waybar
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = swaync
exec-once = swaybg -i /home/ian/Pictures/wallpapers/wpp.png -m fill
exec-once = systemctl --user start hyprpolkitagent
exec-once = pgrep -x nm-applet || nm-applet --indicator
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
