exec-once = waybar
exec-once = swaync
exec-once = swaybg -i /home/ian/Pictures/wallpapers/donati_v3.jpg -m fill
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
